{"uid":"4b4757e66a1912dae1a509f688f20b0f","name":"categories","children":[{"name":"Test defects","children":[{"name":"sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2003, \"Can't connect to MySQL server on 'rm-d9jbw9r6mim1jv8n2wo.mysql.ap-southeast-5.rds.aliyuncs.com' ([Errno 11001] getaddrinfo failed)\")\n(Background on this error at: https://sqlalche.me/e/14/e3q8)","children":[{"name":"[TC-19] Login dengan semua user partner **PARTNER**","uid":"8609d6238880691a","parentUid":"4bfa67ba1ec62bf26d64b5830d0c9f57","status":"broken","time":{"start":1687071202608,"stop":1687072166510,"duration":963902},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"4bfa67ba1ec62bf26d64b5830d0c9f57"}],"uid":"bdbf199525818fae7a8651db9eafe741"}]}